# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-03-29 02:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migration_monitor', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE INDEX user_first_name_index ON migration_monitor_user (first_name)",
            reverse_sql="DROP INDEX user_first_name_index",
        ),
    ]
